(async function () {
  const passed=[];
  const check=(ok,label)=>{if(!ok)throw new Error(label);passed.push(label)};
  const settle=()=>new Promise(r=>setTimeout(r,100));
  const weapon=w=>document.querySelector(`[data-weapon="${w}"]`).click();
  const query=q=>{const i=document.querySelector('#search');i.value=q;i.dispatchEvent(new Event('input',{bubbles:true}))};
  const first=()=>document.querySelector('.case-card')?.getAttribute('href');
  location.hash='/';await settle();weapon('epee');query('');
  check(document.querySelectorAll('.case-card').length===62,'62 épée situations');
  check(!document.querySelector('#category-filter').open,'filters initially collapsed');
  check(document.querySelector('#category-filter summary').textContent.includes('All categories'),'filter summary shows selection');
  check(!document.querySelector('#focus-search') && document.querySelectorAll('.bottom-nav a').length===3,'no redundant Search navigation');
  query('hit floor not foot');check(first()==='#/case/floor-touch','floor lookup');
  document.querySelector('.case-card').click();await settle();
  check(document.querySelector('h1').textContent.includes('floor'),'floor detail route');
  check(document.querySelector('#screen').textContent.includes('does not prove'),'successful test is not proof of location');
  check(document.querySelectorAll('blockquote').length>=8,'source wording bundled');
  check(document.querySelector('#screen').textContent.includes('USA local/division grounding'),'domestic grounding source bundled');
  let s=document.querySelector('[data-fact]');s.value='unclear';s.dispatchEvent(new Event('change',{bubbles:true}));
  check(document.querySelector('#fact-status').textContent.includes('1 unclear'),'fact notes descriptive');
  document.querySelector('[data-clear-facts]').click();check(!s.value,'clear fact notes');
  query('reel disconnected');await settle();check(first()==='#/case/missing-light','search from a detail');
  document.querySelector('.case-card').click();await settle();
  check(document.querySelector('#screen').textContent.includes('retaining safety device'),'body-cord exception explained');
  check(document.querySelector('#screen').textContent.includes('does not award an unregistered touch'),'no invented missing point');
  weapon('foil');check(document.querySelector('[data-switch="epee"]'),'cross-weapon deep link guarded');
  location.hash='/';await settle();query('grounded strip');check(!document.querySelector('[href="#/case/floor-touch"]'),'épée fault does not leak into foil');
  query('white light');check(first()==='#/case/foil-off-target','foil white light');
  weapon('sabre');query('leg hit');check(first()==='#/case/sabre-off-target','sabre off-target');
  check(localStorage.getItem('fencing-scoring-weapon')==='sabre','weapon saved');
  location.hash='/review';await settle();
  check(document.querySelector('#screen').textContent.includes('Head Referee'),'Head Referee identifies domestic reviewability');
  check(document.querySelector('#screen').textContent.includes('the fencer or team captain'),'correct requesters');
  check(document.querySelector('#screen').textContent.includes('full Bout Committee'),'domestic appellate route');
  check(document.querySelector('#screen').textContent.includes('Stay hooked up'),'domestic timing');
  check(document.querySelector('#screen').textContent.includes('Correct the recorded score'),'scoresheet route separate');
  weapon('epee');query('ran past');await settle();document.querySelector('.case-card').click();await settle();
  document.querySelector('[data-step="2"]').click();check(document.querySelector('#diagram-caption').textContent.includes('A’s touch made after passing is annulled'),'passing example role distinction');
  query('fencing time');await settle();
  check(!!document.querySelector('[href="#/case/priority-glossary"]'),'fencing-time concept retrieved');
  check(!!document.querySelector('[href="#/case/ask-time"]'),'clock-time meaning also retrieved');
  query('14 14');await settle();check(first()==='#/case/de-final-double','14–14 finishing double retrieved');
  document.querySelector('.case-card').click();await settle();
  check(document.querySelector('#screen').textContent.includes('score stays 14–14'),'finishing double cancels points');
  check(document.querySelector('#screen').textContent.includes('not a standalone rule amendment'),'corroborating report identified');
  query('4 4 double');await settle();check(first()==='#/case/pool-four-all','pool finishing double retrieved');
  document.querySelector('.case-card').click();await settle();
  check(document.querySelector('#screen').textContent.includes('score stays 4–4'),'pool exception explained');
  check(document.querySelector('.related-cases a[href="#/case/overtime"]'),'related overtime linked');
  document.querySelector('.related-cases a[href="#/case/overtime"]').click();await settle();
  check(document.querySelector('h1').textContent.includes('extra minute'),'related case route');
  query('after buzzer');await settle();check(first()==='#/case/time-expired','time-expiry search');
  document.querySelector('.case-card').click();await settle();
  check(document.querySelector('#screen').textContent.includes('ordinary exception'),'Halt/time distinction visible');
  query('wrong pool score');await settle();document.querySelector('.case-card').click();await settle();
  check(document.querySelector('#screen').textContent.includes('Athlete Handbook'),'domestic source edition visible');
  check(document.querySelector('.rule-link').href.includes('#page=82'),'domestic source points to physical PDF page');
  location.hash='/';await settle();query('');
  document.querySelector('#category-filter').open=true;await settle();
  document.querySelector('[data-category="Score & time"]').click();
  document.querySelector('#category-filter').open=false;await settle();
  check(document.querySelector('#category-filter summary').textContent.includes('Score & time'),'active filter stays visible while collapsed');
  check(Array.from(document.querySelectorAll('.case-card .tag')).every(e=>e.textContent==='Score & time'),'category strictly limits results');
  document.querySelector('#category-filter').open=true;await settle();
  document.querySelector('[data-category="All"]').click();
  document.querySelector('#category-filter').open=false;await settle();
  check(document.querySelector('.companion').getAttribute('href')==='../','reciprocal penalty link');
  check(document.documentElement.scrollWidth<=innerWidth,'no horizontal overflow');
  await navigator.serviceWorker.ready;
  check((await navigator.serviceWorker.getRegistrations()).some(r=>r.scope.endsWith('/scoring/')),'scoring worker scope');
  const cache=await caches.open('fencing-scoring-v10');check(await cache.match(new URL('data/cases.json',location.href).href),'scoring data cached');
  location.hash='/coverage';await settle();
  check(document.querySelectorAll('.coverage-topic').length>30,'coverage map shown for selected weapon');
  check(document.querySelector('[data-coverage="partial"]'),'partial coverage is explicit');
  weapon('foil');check(document.querySelector('#screen').textContent.includes('Written conventions'),'priority scope visible in coverage');
  weapon('epee');query('');await settle();
  return {passed:passed.length,checks:passed};
})()
