(async function () {
  const passed=[];
  const check=(ok,label)=>{if(!ok)throw new Error(label);passed.push(label)};
  const settle=()=>new Promise(r=>setTimeout(r,100));
  const weapon=w=>document.querySelector(`[data-weapon="${w}"]`).click();
  const query=q=>{const i=document.querySelector('#search');i.value=q;i.dispatchEvent(new Event('input',{bubbles:true}))};
  const first=()=>document.querySelector('.case-card')?.getAttribute('href');
  location.hash='/';await settle();weapon('epee');query('');
  check(document.querySelectorAll('.case-card').length===6,'six épée situations');
  query('hit floor not foot');check(first()==='#/case/floor-touch','floor lookup');
  document.querySelector('.case-card').click();await settle();
  check(document.querySelector('h1').textContent.includes('floor'),'floor detail route');
  check(document.querySelector('#screen').textContent.includes('does not prove'),'successful test is not proof of location');
  check(document.querySelectorAll('blockquote').length>=8,'source wording bundled');
  let s=document.querySelector('[data-fact]');s.value='unclear';s.dispatchEvent(new Event('change',{bubbles:true}));
  check(document.querySelector('#fact-status').textContent.includes('1 unclear'),'fact notes descriptive');
  document.querySelector('[data-clear-facts]').click();check(!s.value,'clear fact notes');
  query('reel disconnected');await settle();check(first()==='#/case/missing-light','search from a detail');
  document.querySelector('.case-card').click();await settle();
  check(document.querySelector('#screen').textContent.includes('retaining safety device'),'body-cord exception explained');
  check(document.querySelector('#screen').textContent.includes('does not award an unregistered touch'),'no invented missing point');
  weapon('foil');check(document.querySelector('[data-switch="epee"]'),'cross-weapon deep link guarded');
  location.hash='/';await settle();query('grounded strip');check(!document.querySelector('[href="#/case/floor-touch"]'),'épée fault does not leak into foil');
  query('white light');check(first()==='#/case/foil-off-target','foil white light');
  weapon('sabre');query('leg hit');check(first()==='#/case/sabre-off-target','sabre off-target');
  check(localStorage.getItem('fencing-scoring-weapon')==='sabre','weapon saved');
  location.hash='/review';await settle();
  check(document.querySelector('#screen').textContent.includes('Head Referee'),'correct review authority');
  check(document.querySelector('#screen').textContent.includes('the fencer or team captain'),'correct requesters');
  weapon('epee');query('ran past');await settle();document.querySelector('.case-card').click();await settle();
  document.querySelector('[data-step="2"]').click();check(document.querySelector('#diagram-caption').textContent.includes('A’s touch made after passing is annulled'),'passing example role distinction');
  check(document.querySelector('.companion').getAttribute('href')==='../','reciprocal penalty link');
  check(document.documentElement.scrollWidth<=innerWidth,'no horizontal overflow');
  await navigator.serviceWorker.ready;
  check((await navigator.serviceWorker.getRegistrations()).some(r=>r.scope.endsWith('/scoring/')),'scoring worker scope');
  const cache=await caches.open('fencing-scoring-v2');check(await cache.match(new URL('data/cases.json',location.href).href),'scoring data cached');
  query('');await settle();
  return {passed:passed.length,checks:passed};
})()
